version: "3.9"

# djjoeplaylister is Defined by Local "Dockerfile", Must Be Rebuilt Each Time
services:
  djjoeplaylister:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8384:80
    restart: always
    environment:
      - SPOTIFY_ID
      - SPOTIFY_SECRET